create table olympics( 
    olym_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    olym_year INTEGER NOT NULL,
    host_ntn NUMBER(4) NOT NULL
);
create table nation( 
    ntn_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ntn_name VARCHAR(100) NOT NULL,
    ntn_continent VARCHAR(100) NOT NULL
);
create table athlete( 
    athl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athl_name VARCHAR(100) NOT NULL,
    athl_dob DATE,
    athl_gender VARCHAR(100) NOT NULL,
    athl_height DECIMAL(20,20) NOT NULL,
    athl_weight DECIMAL(20,20) NOT NULL,
    ntn_id INTEGER NOT NULL
);
create table host_ntn_application( 
    host_appl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_amount DECIMAL(20,20) NOT NULL,
    bid_year INTEGER NOT NULL,
    appl_date Timestamp NOT NULL,
    status VARCHAR(20),
    ntn_id INTEGER NOT NULL
);
create table athl_application( 
    athl_appl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appl_date Timestamp NOT NULL,
    status VARCHAR(20),
    athl_id INTEGER NOT NULL,
    sport_id INTEGER NOT NULL,
    ntn_id INTEGER NOT NULL
);
create table event( 
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(100) NOT NULL,
    event_date DATE,
    event_type VARCHAR(20) NOT NULL,
    event_gender VARCHAR(20) NOT NULL,
    sport_id INTEGER NOT NULL
);
create table event_match( 
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    em_date DATE,
    event_id INTEGER NOT NULL,
    venue_id INTEGER NOT NULL,
    olym_id INTEGER NOT NULL
);
create table venue( 
    venue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR(255) NOT NULL,
    venue_capacity INTEGER NOT NULL
);
create table group_match( 
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_type VARCHAR(100) NOT NULL
);
create table sport( 
    sport_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_name VARCHAR(100) NOT NULL
);
create table group_athlete( 
    athl_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL
);
create table athlete_event( 
    athl_id INTEGER NOT NULL ,
    event_id INTEGER NOT NULL
);
create table nation_list( 
    ntn_id INTEGER NOT NULL,
    olym_id INTEGER NOT NULL
);
create table group_match_result( 
    group_id INTEGER NOT NULL PRIMARY KEY,
    match_id INTEGER NOT NULL,
    score decimal(20,20) NOT NULL,
    player_position INTEGER NOT NULL,
    medal_type VARCHAR(20) NOT NULL
);
Alter table host_ntn_application ADD olym_id INTEGER NOT NULL;
alter table host_ntn_application modify bid_year VARCHAR(100);
alter table host_ntn_application modify bid_amount decimal(38,20);
alter table athlete modify athl_height decimal(38,20);
alter table athlete modify athl_weight decimal(38,20);
alter table group_match_result modify score decimal(38,20);
alter table olympics add foreign key(host_ntn) references nation(ntn_id);
alter table host_ntn_application add foreign key(olym_id) references olympics(olym_id);
alter table host_ntn_application add foreign key(ntn_id) references nation(ntn_id);
alter table athl_application add foreign key(athl_id) references athlete(athl_id);
alter table athl_application add foreign key(ntn_id) references nation(ntn_id);
alter table athl_application add foreign key(athl_id) references athlete(athl_id);
alter table athl_application add foreign key(sport_id) references sport(sport_id);
alter table athlete add foreign key(ntn_id) references nation(ntn_id);
alter table event add foreign key(sport_id) references sport(sport_id);
alter table event_match add foreign key(event_id) references event(event_id);
alter table event_match add foreign key(venue_id) references venue(venue_id);
alter table event_match add foreign key(olym_id) references olympics(olym_id);
alter table athlete_event add foreign key(athl_id) references athlete(athl_id);
alter table athlete_event add foreign key(event_id) references event(event_id);
alter table group_athlete add foreign key(group_id) references group_match(group_id);
alter table group_athlete add foreign key(athl_id) references athlete(athl_id);
alter table nation_list add foreign key(ntn_id) references nation(ntn_id);
alter table nation_list add foreign key(olym_id) references olympics(olym_id);


INSERT ALL
    INTO olympics (olym_id, olym_year, host_ntn) VALUES (1, '2021', 1)
    INTO olympics (olym_id, olym_year, host_ntn) VALUES (2, '2016', 2)
    INTO olympics (olym_id, olym_year, host_ntn) VALUES (3, '2012', 3)
    INTO olympics (olym_id, olym_year, host_ntn) VALUES (4, '2008', 4)
    INTO olympics (olym_id, olym_year, host_ntn) VALUES (5, '2004', 5)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (1, 'Greece', 'Europe')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (2, 'USA', 'North America')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (3, 'England', 'Europe')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (4, 'Brazil', 'South America')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (5, 'Japan', 'Asia')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (8, 'Konaha', 'Fire')
    INTO nation (ntn_id, ntn_name, ntn_continent) VALUES (9, 'Gotham', 'North America')

    SELECT 1 FROM dual
;
INSERT ALL
    INTO group_match (group_id, group_type) VALUES (1, 'Single')
    INTO group_match (group_id, group_type) VALUES (2, 'Multiple')
    INTO group_match (group_id, group_type) VALUES (3, 'Multiple')
    INTO group_match (group_id, group_type) VALUES (4, 'Single')
    SELECT 1 FROM dual
;
INSERT ALL
    INTO sport (sport_id, sport_name) VALUES (1, 'Aquatics')
    INTO sport (sport_id, sport_name) VALUES (2, 'Athletics')
    INTO sport (sport_id, sport_name) VALUES (3, 'Gymnastics')
    INTO sport (sport_id, sport_name) VALUES (4, 'Running')
    INTO sport (sport_id, sport_name) VALUES (5, 'Jumping')
    SELECT 1 FROM dual
;
INSERT ALL
    INTO venue (venue_id, venue_name, venue_capacity) VALUES (1, 'Estadio Stadium', 60000)
    INTO venue (venue_id, venue_name, venue_capacity) VALUES (2, 'Marathon City Stadium', 72000)
    INTO venue (venue_id, venue_name, venue_capacity) VALUES (3, 'White City Stadium', 80000)
    INTO venue (venue_id, venue_name, venue_capacity) VALUES (4, 'Riverside Stadium', 55000)
    INTO venue (venue_id, venue_name, venue_capacity) VALUES (5, 'Empire Stadium', 58000)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (2 , 350000.34, '2021', '25-nov-2020', 2, 1)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (3 , 325000.45, '2021', '30-nov-2020', 3, 1)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (4 , 370000.32, '2021', '23-nov-2020', 4, 1)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (5 , 350000.46, '2016', '20-oct-2015', 1, 2)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (6 , 330000.23, '2016', '14-oct-2015', 3, 2)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (7 , 313500, '2016', '12-oct-2015', 2, 2)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (8 , 33000, '2016', '19-oct-2015', 8, 2)
    INTO host_ntn_application (host_appl_id, bid_amount, bid_year, appl_date, ntn_id, olym_id) VALUES (9 , 34000.54, '2016', '23-oct-2015', 9, 2)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (1 , '02-nov-2020', 1, 1, 1)
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (2 , '05-nov-2020', 1, 1, 2)
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (3 , '10-nov-2020', 2, 1, 1)
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (4 , '13-nov-2020', 3, 1, 1)
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (5 , '03-nov-2020', 3, 1, 5)
    INTO athl_application (athl_appl_id, appl_date, athl_id, ntn_id, sport_id) VALUES (6 , '23-nov-2020', 1, 1, 4)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (2 , 'Nicholas Green', '08-nov-1994', 'M', 190.4, 60.5, 1)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (3 , 'Maria Adamos', '04-nov-1990', 'F', 170, 45, 1)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (4 , 'James Smith', '09-sep-1992', 'M', 195.3, 65.2, 2)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (5 , 'Maria Gracia', '05-june-1993', 'F', 172.9, 50.6, 2)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (6 , 'Mary Smith', '02-oct-1993', 'F', 175 , 52.3, 2)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (7 , 'Jack Oliver', '18-feb-1998', 'M', 180.2, 55.1, 3)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (8 , 'Jacob Cullen', '10-dec-1997', 'M', 185.9, 57.8, 3)
    INTO athlete (athl_id, athl_name, athl_dob, athl_gender, athl_height, athl_weight, ntn_id) VALUES (9 , 'Olivia Smith', '30-sep-1995', 'F', 183.6, 56, 3)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (1 , 'Swimming', 'Single', 'M', 1)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (2 , 'Water Polo', 'Multiple', 'M', 1)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (3 , 'Diving', 'Single', 'F', 1)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (4 , '100M Race', 'Single', 'M', 2)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (5 , '400M Race', 'Single', 'M', 2)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (6 , 'Shot Put', 'Single', 'F', 2)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (7 , 'Floor Exercises', 'Single', 'M', 3)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (8 , 'Rings', 'Single', 'F', 3)
    INTO event (event_id, event_name, event_type, event_gender, sport_id) VALUES (9 , 'Vault', 'Single', 'F', 3)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (1 , '01-may-2021', 1, 1, 1)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (2 , '10-may-2021', 2, 1, 1)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (3 , '15-may-2021', 2, 1, 1)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (4 , '25-may-2021', 4, 1, 1)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (5 , '01-feb-2016', 1, 2, 2)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (6 , '15-feb-2016', 3, 2, 2)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (7 , '03-mar-2016', 3, 2, 2)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (8 , '10-aug-2012', 8, 3, 3)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (9 , '25-aug-2012', 2, 3, 3)
    INTO event_match (match_id, em_date, event_id, venue_id, olym_id) VALUES (10 , '01-sep-2012', 2, 3, 3)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO group_match_result (group_id, match_id, score, player_position, medal_type) VALUES (1 , 1, 99.5, 1 , 'Gold')
    INTO group_match_result (group_id, match_id, score, player_position, medal_type) VALUES (2 , 1, 95.4, 2, 'Silver')
    INTO group_match_result (group_id, match_id, score, player_position, medal_type) VALUES (2 , 1, 89, 10,  'None')
    INTO group_match_result (group_id, match_id, score, player_position, medal_type) VALUES (4 , 1, 92.2, 3, 'Bronze')
    SELECT 1 FROM dual
;
INSERT ALL
    INTO athlete_event (athl_id, event_id) VALUES (1 , 1)
    INTO athlete_event (athl_id, event_id) VALUES (1 , 2)
    INTO athlete_event (athl_id, event_id) VALUES (2 , 2)
    INTO athlete_event (athl_id, event_id) VALUES (3 , 3)
    INTO athlete_event (athl_id, event_id) VALUES (3 , 5)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO group_athlete (athl_id, group_id) VALUES (1 , 1)
    INTO group_athlete (athl_id, group_id) VALUES (1 , 2)
    INTO group_athlete (athl_id, group_id) VALUES (2 , 2)
    INTO group_athlete (athl_id, group_id) VALUES (3 , 4)
    SELECT 1 FROM dual
;
INSERT ALL
    INTO nation_list (olym_id, ntn_id) VALUES (1 , 1)
    INTO nation_list (olym_id, ntn_id) VALUES (1 , 2)
    INTO nation_list (olym_id, ntn_id) VALUES (1 , 3)
    INTO nation_list (olym_id, ntn_id) VALUES (2 , 1)
    INTO nation_list (olym_id, ntn_id) VALUES (2 , 4)
    INTO nation_list (olym_id, ntn_id) VALUES (2 , 5)
    INTO nation_list (olym_id, ntn_id) VALUES (3 , 1)
    INTO nation_list (olym_id, ntn_id) VALUES (3 , 2)
    INTO nation_list (olym_id, ntn_id) VALUES ( 3, 3)
    SELECT 1 FROM dual
;

commit;
